#include "led.h"

void LED_control(u8 LED_CO)
{
	 HAL_GPIO_WritePin(GPIOC,0XFF00,GPIO_PIN_SET);
	   HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET);
	   HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET);
	
	HAL_GPIO_WritePin(GPIOC,LED_CO<<8,GPIO_PIN_RESET);
	   HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET);
	   HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET);
}
